const express = require('express')
const router = express.Router()
const authRoutes = require('./auth.route')
const applicationRoutes = require('./applications.route')
const ecourtRoutes = require('./ecourts.route')
const employeeRoutes = require('./employees.route')
const historyRoutes = require('./histories.route')
const queueRoutes = require('./queues.route')
const sessionRoutes = require('./sessions.route')
const roleRoutes = require('./roles.route')
const userRoutes = require('./users.route')
const profileRoutes = require('./profiles.route')
const partnerRoutes = require('./partners.route')
const sharing_applicationRoutes = require('./sharing_applications.route')

router.use('/auth', authRoutes)
router.use('/applications', applicationRoutes)
router.use('/ecourts', ecourtRoutes)
router.use('/employees', employeeRoutes)
router.use('/histories', historyRoutes)
router.use('/queues', queueRoutes)
router.use('/roles', roleRoutes)
router.use('/sessions', sessionRoutes)
router.use('/users', userRoutes)
router.use('/profiles', profileRoutes)
router.use('/partners', partnerRoutes)
router.use('/sharing-applications', sharing_applicationRoutes)

module.exports = router